AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Exported by architect/package@6.0.4 on 2021-01-28T20:29:17.597Z
Resources:
  EtljobScheduledLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://etl-template-cfn-deployments-1b400/5ad6578a4c8b8542ea3fc9035966cf4c
      Runtime: nodejs12.x
      MemorySize: 1152
      Timeout: 200
      Environment:
        Variables:
          ARC_APP_NAME: etl-template
          ARC_CLOUDFORMATION:
            Ref: AWS::StackName
          ARC_ENV: staging
          ARC_HTTP: aws_proxy
          ARC_ROLE:
            Ref: Role
          NODE_ENV: staging
          SESSION_TABLE_NAME: jwe
      Role:
        Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${roleName}
        - roleName:
            Ref: Role
      Events: {}
  EtljobScheduledEvent:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 minute)
      Targets:
      - Arn:
          Fn::GetAtt:
          - EtljobScheduledLambda
          - Arn
        Id: EtljobScheduledLambda
  EtljobScheduledPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: EtljobScheduledLambda
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - EtljobScheduledEvent
        - Arn
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: ArcGlobalPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Resource: arn:aws:logs:*:*:*
Outputs: {}
